"""Deterministic synthetic media with ground-truth manifests (clearly labeled synthetic).

Fixture media is produced from a :class:`FixtureSpec` with FFmpeg ``lavfi`` drawing (video) and
NumPy synthesis (audio). Generation code is independent of the renderer and the compiler: it never
imports :mod:`ave.render` or :mod:`ave.domain`, so expected values derived from a manifest stay an
independent oracle.

Video frames show a source-specific background color, the frame-index barcode of
:mod:`ave.fixtures.barcode`, and a one-frame full-white background flash on every event frame.
Audio carries a low-level pilot tone (source identification), a broadband chirp starting exactly at
every event time (sync and timing evidence), an overall gain and optional seeded white noise.

Results are cached under ``var/fixtures/<name>-<hash>/`` where the hash covers the specification,
the generator version and the FFmpeg version; a cache entry is reused only when its file still
matches the recorded SHA-256. Each entry holds the media file and ``manifest.json``.
"""

from __future__ import annotations

import functools
import hashlib
import json
import math
import shutil
import uuid
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any, Literal

import numpy as np
import numpy.typing as npt
from pydantic import BaseModel, ConfigDict, Field, model_validator

from ave.fixtures.barcode import CELLS, barcode_layout, ffmpeg_bit_expression
from ave.media.asset import sha256_file
from ave.paths import fixtures_root
from ave.proc import ffmpeg_version, media_url, run_tool
from ave.timebase import PositiveRational, Rational, rational_to_json

__all__ = [
    "CHIRP_DURATION_S",
    "CHIRP_F0_HZ",
    "CHIRP_F1_HZ",
    "GENERATOR_VERSION",
    "SYNTHETIC_LABEL",
    "VFR_TICK_RATE",
    "AudioSpec",
    "Fixture",
    "FixtureSpec",
    "VideoSpec",
    "chirp",
    "ensure_fixture",
    "generator_digest",
    "synthesize_audio",
    "vfr_frame_ticks",
]

GENERATOR_VERSION = 1
SYNTHETIC_LABEL = "SYNTHETIC TEST FIXTURE generated by ave.fixtures - not user footage"

CHIRP_DURATION_S = 0.012
CHIRP_F0_HZ = 500.0
CHIRP_F1_HZ = 7000.0

VFR_TICK_RATE = 120
"""Time base (ticks per second) of variable-frame-rate fixtures."""

_TIMEOUT_S = 900.0


@functools.cache
def generator_digest() -> str:
    """Digest of the generator's own source files.

    It is part of every cache key, so an edited generator writes new files and a test never passes
    on the files an earlier generator left in the cache.
    """
    package = Path(__file__).resolve().parent
    digest = hashlib.sha256()
    for name in ("barcode.py", "generate.py", "standard.py"):
        digest.update((package / name).read_bytes())
    return digest.hexdigest()[:16]


class _Frozen(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")


class AudioSpec(_Frozen):
    """One synthetic audio stream."""

    sample_rate: int = Field(ge=8000, le=192000)
    channels: int = Field(default=1, ge=1, le=8)
    pilot_hz: float = Field(gt=0)
    pilot_amplitude: float = Field(default=0.05, ge=0, le=1)
    event_amplitude: float = Field(default=0.5, ge=0, le=1)
    gain: float = Field(default=1.0, gt=0, le=4)
    noise_rms: float = Field(default=0.0, ge=0, le=1)
    seed: int = 0
    codec: Literal["aac", "pcm_s16le"] = "aac"


class VideoSpec(_Frozen):
    """The synthetic video stream."""

    width: int = Field(ge=16, le=8192)
    height: int = Field(ge=16, le=8192)
    fps: PositiveRational
    """Nominal rate; for VFR fixtures the frames are re-timed with :func:`vfr_frame_ticks`."""
    color: tuple[int, int, int]
    """Background RGB (identifies the source)."""
    rotation: int = 0
    """Display-matrix rotation written as metadata (the pixels are not rotated)."""
    sar: PositiveRational = Fraction(1)
    vfr: bool = False


class FixtureSpec(_Frozen):
    """Everything that determines one fixture file."""

    name: str = Field(pattern=r"^[a-z0-9][a-z0-9_-]*$")
    description: str
    duration: PositiveRational
    container: Literal["mp4", "m4a", "png"] = "mp4"
    video: VideoSpec | None = None
    audio: tuple[AudioSpec, ...] = ()
    events: tuple[Rational, ...] = ()
    """Event times in source seconds: a flash frame and a chirp onset at each."""

    @model_validator(mode="after")
    def _consistent(self) -> FixtureSpec:
        if self.video is None and not self.audio:
            raise ValueError("a fixture needs video or audio")
        if self.container == "png" and (self.video is None or self.audio):
            raise ValueError("png fixtures hold exactly one picture")
        if self.container == "m4a" and self.video is not None:
            raise ValueError("m4a fixtures are audio-only")
        for event in self.events:
            if not 0 <= event < self.duration:
                raise ValueError(f"event {event} outside [0, {self.duration})")
            if self.video is not None and not self.video.vfr and (event * self.video.fps) % 1:
                raise ValueError(f"event {event} is not on the video frame grid")
            for audio in self.audio:
                if (event * audio.sample_rate) % 1:
                    raise ValueError(f"event {event} is not on the {audio.sample_rate} Hz grid")
        return self

    def cache_key(self) -> str:
        """Hash of the specification, the generator (version and sources) and the FFmpeg version."""
        payload = json.dumps(
            {
                "spec": self.model_dump(mode="json"),
                "generator": GENERATOR_VERSION,
                "sources": generator_digest(),
                "ffmpeg": ffmpeg_version(),
            },
            sort_keys=True,
        )
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


@dataclass(frozen=True)
class Fixture:
    """A generated fixture file and its ground-truth manifest."""

    spec: FixtureSpec
    path: Path
    sha256: str
    manifest: dict[str, Any]


# --------------------------------------------------------------------------------------------
# Signal definitions (shared with test oracles through the manifest parameters)
# --------------------------------------------------------------------------------------------


def chirp(sample_rate: int) -> npt.NDArray[np.float64]:
    """Unit-amplitude Hann-windowed linear chirp (500 Hz to 7 kHz over 12 ms)."""
    count = round(CHIRP_DURATION_S * sample_rate)
    t = np.arange(count) / sample_rate
    sweep = (CHIRP_F1_HZ - CHIRP_F0_HZ) / (2 * CHIRP_DURATION_S)
    window = np.sin(np.pi * np.arange(count) / count) ** 2
    result: npt.NDArray[np.float64] = window * np.sin(2 * np.pi * (CHIRP_F0_HZ * t + sweep * t * t))
    return result


def synthesize_audio(
    spec: AudioSpec, duration: Fraction, events: tuple[Fraction, ...]
) -> npt.NDArray[np.float32]:
    """Samples ``(n, channels)`` float32: gain * (pilot + chirps) + seeded white noise."""
    count = math.ceil(duration * spec.sample_rate)
    t = np.arange(count, dtype=np.float64) / spec.sample_rate
    signal = spec.pilot_amplitude * np.sin(2 * np.pi * spec.pilot_hz * t)
    burst = spec.event_amplitude * chirp(spec.sample_rate)
    for event in events:
        start = int(event * spec.sample_rate)
        end = min(count, start + len(burst))
        signal[start:end] += burst[: end - start]
    signal *= spec.gain
    if spec.noise_rms > 0:
        signal += spec.noise_rms * np.random.default_rng(spec.seed).standard_normal(count)
    mono = signal.astype(np.float32)
    samples: npt.NDArray[np.float32] = np.repeat(mono[:, None], spec.channels, axis=1)
    return samples


def vfr_frame_ticks(duration: Fraction) -> list[int]:
    """PTS (in 1/120 s ticks) of a deterministic irregular frame sequence covering ``duration``.

    Frame 0 is at 0; frame ``n`` follows frame ``n - 1`` after ``1 + ((7 n^2 + 3 n) mod 5)`` ticks,
    so frame intervals vary between 1/120 s and 5/120 s without a short period.
    """
    limit = duration * VFR_TICK_RATE
    ticks = [0]
    n = 1
    while True:
        nxt = ticks[-1] + 1 + (7 * n * n + 3 * n) % 5
        if nxt >= limit:
            return ticks
        ticks.append(nxt)
        n += 1


# --------------------------------------------------------------------------------------------
# FFmpeg graph construction
# --------------------------------------------------------------------------------------------


def _hex(color: tuple[int, int, int]) -> str:
    return "0x" + "".join(f"{max(0, min(255, c)):02X}" for c in color)


def _video_graph(spec: FixtureSpec, video: VideoSpec) -> tuple[str, int | None]:
    """Filter script drawing the fixture video; returns ``(script, vfr_frame_count)``."""
    layout = barcode_layout(video.width, video.height)
    rate = f"{video.fps.numerator}/{video.fps.denominator}"
    vfr_ticks = vfr_frame_ticks(spec.duration) if video.vfr else None
    source_rate = str(VFR_TICK_RATE) if video.vfr else rate
    parts = [
        f"color=c={_hex(video.color)}:s={video.width}x{video.height}:r={source_rate}:"
        f"d={float(spec.duration) + 1}",
        "format=rgb24",
    ]
    if spec.events:
        if vfr_ticks is not None:
            flash_frames = [
                i
                for i, tick in enumerate(vfr_ticks)
                if Fraction(tick, VFR_TICK_RATE) in spec.events
            ]
        else:
            flash_frames = [int(event * video.fps) for event in spec.events]
        if flash_frames:
            condition = "+".join(f"eq(n,{frame})" for frame in flash_frames)
            parts.append(f"drawbox=x=0:y=0:w=iw:h=ih:color=white:t=fill:enable='{condition}'")
    parts.append(
        f"drawbox=x={layout.x0}:y={layout.y0}:w={layout.grid_size}:h={layout.grid_size}:"
        "color=black:t=fill"
    )
    for cell in range(CELLS):
        x, y, width, height = layout.cell_rect(cell)
        parts.append(
            f"drawbox=x={x}:y={y}:w={width}:h={height}:color=white:t=fill:"
            f"enable='{ffmpeg_bit_expression(cell)}'"
        )
    if video.sar != 1:
        parts.append(f"setsar={video.sar.numerator}/{video.sar.denominator}")
    if vfr_ticks is not None:
        parts.append(f"trim=end_frame={len(vfr_ticks)}")
        parts.append(f"settb=1/{VFR_TICK_RATE}")
        parts.append("setpts=if(eq(N\\,0)\\,0\\,PREV_OUTPTS+1+mod(7*N*N+3*N\\,5))")
    else:
        frames = math.ceil(spec.duration * video.fps)
        parts.append(f"trim=end_frame={frames}")
    if spec.container == "png":
        parts.append("trim=end_frame=1")
    else:
        parts.append("scale=out_color_matrix=bt709:out_range=tv")
        parts.append("format=yuv420p")
    return ",".join(parts) + "[vout]\n", (len(vfr_ticks) if vfr_ticks is not None else None)


def _encode(spec: FixtureSpec, work: Path, output: Path) -> dict[str, Any]:
    args = ["-hide_banner", "-nostdin", "-v", "error", "-y"]
    extra: dict[str, Any] = {}
    inputs = 0
    if spec.video is not None:
        script, vfr_frames = _video_graph(spec, spec.video)
        script_path = work / "video.filter"
        script_path.write_text(script, encoding="utf-8")
        args += ["-filter_complex_script", str(script_path)]
        if vfr_frames is not None:
            extra["vfr_frame_ticks"] = vfr_frame_ticks(spec.duration)
            extra["vfr_tick_rate"] = VFR_TICK_RATE
    for index, audio in enumerate(spec.audio):
        raw = work / f"audio{index}.f32"
        synthesize_audio(audio, spec.duration, spec.events).tofile(raw)
        args += [
            "-f", "f32le", "-ar", str(audio.sample_rate), "-ac", str(audio.channels),
            "-i", media_url(raw),
        ]  # fmt: skip
        inputs += 1
    if spec.video is not None:
        args += ["-map", "[vout]"]
    for index in range(inputs):
        args += ["-map", f"{index}:a:0"]
    if spec.container == "png":
        args += ["-frames:v", "1", "-f", "image2", "-c:v", "png", media_url(output)]
        run_tool("ffmpeg", args, timeout=_TIMEOUT_S)
        return extra
    if spec.video is not None:
        video = spec.video
        gop = max(1, round(video.fps))
        args += [
            "-c:v", "libx264", "-preset", "veryfast", "-crf", "12", "-g", str(gop),
            "-pix_fmt", "yuv420p", "-color_primaries", "bt709", "-color_trc", "bt709",
            "-colorspace", "bt709", "-color_range", "tv",
        ]  # fmt: skip
        if video.vfr:
            args += ["-fps_mode", "passthrough", "-video_track_timescale", str(VFR_TICK_RATE)]
    for index, audio in enumerate(spec.audio):
        if audio.codec == "aac":
            args += [f"-c:a:{index}", "aac", f"-b:a:{index}", "256k"]
        else:
            args += [f"-c:a:{index}", "pcm_s16le"]
    container = "mp4" if spec.container == "mp4" else "ipod"
    if spec.video is not None and spec.video.rotation:
        staged = work / f"unrotated.{spec.container}"
        run_tool("ffmpeg", [*args, "-f", container, media_url(staged)], timeout=_TIMEOUT_S)
        run_tool(
            "ffmpeg",
            [
                "-hide_banner", "-nostdin", "-v", "error", "-y",
                "-display_rotation", str(spec.video.rotation), "-i", media_url(staged),
                "-map", "0", "-c", "copy", "-f", container, media_url(output),
            ],
            timeout=_TIMEOUT_S,
        )  # fmt: skip
    else:
        run_tool("ffmpeg", [*args, "-f", container, media_url(output)], timeout=_TIMEOUT_S)
    return extra


def _manifest(
    spec: FixtureSpec, file_name: str, checksum: str, extra: dict[str, Any]
) -> dict[str, Any]:
    manifest: dict[str, Any] = {
        "synthetic": True,
        "label": SYNTHETIC_LABEL,
        "generator_version": GENERATOR_VERSION,
        "ffmpeg": ffmpeg_version(),
        "file": file_name,
        "sha256": checksum,
        "spec": spec.model_dump(mode="json"),
        "chirp": {
            "duration_s": CHIRP_DURATION_S,
            "f0_hz": CHIRP_F0_HZ,
            "f1_hz": CHIRP_F1_HZ,
            "window": "hann",
            "onset": "event time is the first chirp sample",
        },
        "events": [rational_to_json(Fraction(e)) for e in spec.events],
        **extra,
    }
    if spec.video is not None:
        layout = barcode_layout(spec.video.width, spec.video.height)
        manifest["barcode"] = {
            "cell": layout.cell,
            "x0": layout.x0,
            "y0": layout.y0,
            "patch": [layout.patch_x, layout.patch_y, layout.patch_size],
        }
    return manifest


def _load_cached(directory: Path, spec: FixtureSpec) -> Fixture | None:
    manifest_path = directory / "manifest.json"
    if not manifest_path.is_file():
        return None
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    path = directory / str(manifest.get("file", ""))
    if not path.is_file() or sha256_file(path) != manifest.get("sha256"):
        return None
    return Fixture(spec=spec, path=path, sha256=str(manifest["sha256"]), manifest=manifest)


def ensure_fixture(spec: FixtureSpec, root: Path | None = None) -> Fixture:
    """Returns the cached fixture for ``spec``, generating it first when needed."""
    base = root or fixtures_root()
    directory = base / f"{spec.name}-{spec.cache_key()}"
    cached = _load_cached(directory, spec)
    if cached is not None:
        return cached
    work = base / f".{spec.name}.tmp-{uuid.uuid4().hex}"
    work.mkdir(parents=True)
    try:
        file_name = f"{spec.name}.{spec.container}"
        extra = _encode(spec, work, work / file_name)
        checksum = sha256_file(work / file_name)
        manifest = _manifest(spec, file_name, checksum, extra)
        (work / "manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8"
        )
        for leftover in work.iterdir():
            if leftover.name not in {file_name, "manifest.json"}:
                leftover.unlink()
        if directory.exists():
            shutil.rmtree(directory)
        work.rename(directory)
    finally:
        if work.exists():
            shutil.rmtree(work, ignore_errors=True)
    fixture = _load_cached(directory, spec)
    if fixture is None:  # pragma: no cover - only on concurrent deletion
        raise RuntimeError(f"fixture {spec.name} vanished after generation")
    return fixture
